version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    commands:
      - echo node --version
      - npm install
    runtime-versions:
      nodejs: 10
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - echo 'Running build' 
      # - command
  build:
    commands:
      - npm run export
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - out/*
    # - location
  #name: $(date +%Y-%m-%d)
  discard-paths: yes
  #base-directory: '/out'
#cache:
  #paths:
    # - paths
